url: https://rinesch.github.io
permalink: :categories/:title/
description: "Sample short description"

timezone: Europe/Zurich

title: Rinesch Murugathas

links:
  - title: Home
    url: /
  - title: Portfolio
    url: /portfolio/
  - title: About
    url: /about/

markdown: kramdown

exclude: [ 'node_modules', 'gulpfile.js', 'package.json', 'LICENSE.md', 'README.md' ]
