url: https://rinesch.github.io
permalink: :categories/:title/
description: "Rinesch Murugathas is an aspiring UX Designer and Coder from Switzerland."
timezone: Europe/Zurich
title: Rinesch Murugathas

markdown: kramdown

links:
  - title: Home
    url: /
  - title: Portfolio
    url: /portfolio/
  - title: About
    url: /about/

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: portfolio
      type: posts
    values:
      layout: post
      match: post

exclude: [ 'node_modules', 'gulpfile.js', 'package.json', 'LICENSE.md', 'README.md' ]
